# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:          
  verify_app:
    name: Verify Application Deploy    
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install PostgreSQL Client
      run: |
        sudo apt-get update
        #echo sudo bash -c "echo deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main >> /etc/apt/sources.list.d/pgdg.list"
        #echo wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        #echo sudo apt-get update
        #echo sudo apt-get -yqq install libpq-dev postgresql-client-11
        sudo apt-get -yqq install postgresql-client
    - name: Remove old Open JDK and install Open JDK 11
      run: |
        sudo apt-get purge AdoptOpenJDK* -yqq
        sudo apt-get purge openjdk* -yqq
        sudo dpkg --list | grep zulu
        sudo dpkg --remove zulu-7-azure-jdk
        sudo apt-get install openjdk-11-jre-headless -y
        echo "Java version: $(java -version)"
    - name: Verifying deployed build
      run: |
        ls -la
        sudo chmod +x softpak/verify_build/build-verification.jar
        cd softpak/verify_build
        java -jar build-verification.jar
      env:
        SERVICE_URL: https://rebalancing-rest.sandbox.blueleaf.com
        APP_URL: https://rebalancing.sandbox.blueleaf.com
        SERVICE_VERSION: 1.0.64.1
        APP_VERSION: 1.0.33
        ENGINE_VERSION: 1.0.39.6
        DB_VERSION: 1.0.64
