# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:          
  verify_app:
    name: Verify Application Deploy    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Verifying deployed build
      run: |
        ls -la
        sudo chmod +x softpak/verify_build/build-verification.jar
        cd softpak/verify_build
        java -jar build-verification.jar
      env:
        SERVICE_URL: https://rebalancing-rest.sandbox.blueleaf.com
        APP_URL: https://rebalancing.sandbox.blueleaf.com
        SERVICE_VERSION: 1.0.64.1
        APP_VERSION: 1.0.33
        ENGINE_VERSION: 1.0.39.6
        DB_VERSION: 1.0.64
